### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by caffeine-potent** [plasticityai/magnitude#11]
Nice project! Any plans for python 3 support?

**Comment by AjayP13** [comment]
Thanks! The project does already support Python 3 (and we run tests against Python 3 as well)! 

Installation is usually `pip3 install pymagnitude` for Python 3 instead of `pip install pymagnitude`.

Are you having any issues / syntax errors using it on Python 3?

**Comment by caffeine-potent** [comment]
Whoops. I don't know how I missed that.   
`pip3 install pymagnitude`
