### ISSUE TITLE
Cache is reusable by another container

### ISSUE THREAD

**Issue by TNorden** [plasticityai/magnitude#17]
I am running pymagnitude inside a docker container.  I mount the magnitude file as a volume on the container but I believe that the cache is written to a temp dir inside the container.  Is it possible to configure where the cache is written to?  I would like to write the to the same volume mounted to the container  so that the next container that starts up can use it as well.

When I develop locally I see that the first load of the magnitude file take s ~120s with the options `lazy_loading=-1` and `blocking=True`.  I am using these options so that my API does not start serving requests until pymagnitude can have consistent response times when running `most_similar()`.  The next time I start the API I see that pymagnitude locally only takes ~300ms load.  However, when I run the api in a docker container the load time is consistently ~120s.  I am assuming the this is because the cache is written to a temp dir.

https://github.com/plasticityai/magnitude/blob/master/pymagnitude/__init__.py#L375-L378

I also maybe completely misunderstanding why sometimes it loads faster locally.

Thanks!

**Comment by AjayP13** [comment]
Yes, that is why. Caches are written to the OS temp directory. If you are using a Docker container, you can just mount a shared host machine folder to the `/tmp/` directory for each of your Docker containers so they share a `/tmp/` directory and it is persistent between Docker runs.

For example:
`docker -v /absolute/path/to/folder/on/host/:/tmp/ -it run name_of_your_container:latest`

**Comment by TNorden** [comment]
Awesome, great idea.  I will test that out and get back to you.  Thanks @AjayP13

**Comment by TNorden** [comment]
@AjayP13 your solution is working perfectly pymagnitude is now loading in ~20s in my docker container.  Thanks for the help!
