### ISSUE TITLE
Can't open db file when creating Magnitude Object

### ISSUE THREAD

**Issue by yassin-taskin** [plasticityai/magnitude#2]
I tried following the instructions, downloaded a db file and tried out the code

```python
vectors = Magnitude(MAG_PATH)
```

The file is definitly there but i got an error
`sqlite3.OperationalError: unable to open database file`

When looking at the code this seems to get executed starting at line 346
```python
    if self.fd:
         conn = sqlite3.connect('/dev/fd/%d' % self.fd,
          check_same_thread=False)
    else:
        conn = sqlite3.connect(self.path, check_same_thread=False)
        self._create_empty_db(conn.cursor())
```

right at the start of the _db() method.

self.fd seems to get set whenever path is not none in the __init__ method
it is the return code of os.open(path)

So the path that is tried to open is "/dev/fd/3/" instead of the actual database path

Seems to work when i change the line
```python
conn = sqlite3.connect('/dev/fd/%d' % self.fd,
          check_same_thread=False)
```

to
```python
conn = sqlite3.connect(self.path,
          check_same_thread=False)
```

**Comment by AjayP13** [comment]
What operating system are you using? macOS and Linux support '/dev/fd/' paths but Windows does not. I wasn't originally targeting support for Windows, but if this is an issue for you I'm happy to fix it to make it compatible.

**Comment by yassin-taskin** [comment]
Yes i'm using windows.

**Comment by yassin-taskin** [comment]
This got fixed in the update. Thanks Ajay.
