### ISSUE TITLE
most_similar() anomalies

### ISSUE THREAD

**Issue by nano5th** [plasticityai/magnitude#23]
Hi, I converted bilingual FastText embeddings into a medium magnitude model and I'm getting some questionable results:

`>>> xlvecs=Magnitude("wiki.+de+en.tag.vec.magnitude")`
`>>> katze=xlvecs.most_similar("katze@de@", topn=5)`
`>>> print(katze)`
`[('rabbit,@en@', 0.3190704584121704), ('dogs,@en@', 0.31559139490127563), ('chickenhound@en@', 0.3059767484664917), ('rabbity@en@', 0.30381107330322266), ('#mouse@en@', 0.29921069741249084)]`
`>>> xlvecs.similarity("katze@de@", "cat@en@")`
`0.4569693`
`>>> xlvecs.similarity("katze@de@", "cats@en@")`
`0.38769498`
`>>> xlvecs.similarity("katze@de@", "dog@en@")`
`0.42773518`
`>>> xlvecs.similarity("katze@de@", "rabbit@en@")`
`0.40975133`

"cat@en@", "cats@en@", "dog@en@" and even actual "rabbit@en@" (no spurious comma) are more similar to "katze@de@" but instead I'm getting "rabbits,@en@". Am I misunderstanding what most_similar is supposed to do?

I thought maybe I could try setting max_distance to just a hair above `xlvecs.distance("katze@de@", "cat@en@)` to see what would happen, but I got `TypeError: most_similar() got an unexpected keyword argument 'max_distance'`

I'm on version  0.1.48

**Comment by AjayP13** [comment]
Hi,

Thanks for reporting this. You're right the documentation was wrong, the argument is not`max_distance` the argument is `min_similarity` (takes in values from -1.0-1.0), but it's a similar concept. I've updated the documentation.

We do have tests for `most_similar`, but that does appear to be broken and I'm not sure why off the top of my head. Would you mind sending me the `.magnitude` file you have somehow? 

Seems like these services might help you transfer large files:
https://wetransfer.com/ (2GB)
https://transfer.pcloud.com/ (5GB)

If you need an e-mail you can use opensource@plasticity.ai.

**Comment by nano5th** [comment]
Thanks for updating the documentation! min_similarity makes much more sense :) 

I'm attempting to send the gzipped file via pcloud right now (slow upload, but hopefully it should get there eventually)

**Comment by AjayP13** [comment]
Thanks, received! I'll investigate what's going on with this file and report back here.
