### ISSUE TITLE
magnitude download feature

### ISSUE THREAD

**Issue by jsedoc** [plasticityai/magnitude#24]
I was wondering if magnitude could have a feature like [NLTK download](https://www.nltk.org/data.html) where embeddings could be downloaded from [your website](https://github.com/plasticityai/magnitude#pre-converted-magnitude-formats-of-popular-embeddings-models).

**Comment by AjayP13** [comment]
This is now out on version 0.1.51, you can upgrade the version of your library to access it. The feature is documented here: https://github.com/plasticityai/magnitude#remote-loading.

**Comment by jsedoc** [comment]
@AjayP13 thanks! This is super useful!
