### ISSUE TITLE
does magnitude support index2word attribute, similar to that of gensim?

### ISSUE THREAD

**Issue by chaitu9701** [plasticityai/magnitude#28]
In Gensim i follow these steps to load word vectors and just retain a unique set of vectors in next step.

```
model = gensim.models.KeyedVectors.load_word2vec_format(GoogleNews-vectors-negative300.bin, limit=100000)
index2word_set = set(model.index2word)
```
In magnitude i load word vectors but how to emulate the index2word?

```
model = Magnitude("crawl-300d-2M.magnitude")
index2word_set = set(model.index) #does not work, 'method' object is not iterable
```

**Comment by AjayP13** [comment]
You can index the keys with `model[5]` to get the "key/value pair tuple" or `model.index(5, return_vector = False)` to just get the key. You can then create a set in Python by doing: 

```python
index2word_set = set([model.index(i, return_vector=False) for i in range(len(model))])
```

Ideally, you should not loop over all vectors like this. It will be slow. Magnitude makes speed enhancements by lazy loading into memory. By doing this, you are asking it to load all of the data back into memory immediately. What's your use case for doing this?

**Comment by AjayP13** [comment]
```python
import numpy
from pymagnitude import *

model = Magnitude("crawl-300d-2M.magnitude")
sent_1 = model.query(["The", "quick", "brown", "fox", "jumped", "over", "the", "lazy", "dog", "."])
sent_1 = numpy.mean(sent_1)/numpy.linalg.norm(sent_1) # average the vectors for each word into a single vector and normalize it
sent_2 = model.query(["The", "quick", "brown", "fox", "jumped", "over", "the", "lazy", "cat", "."])
sent_2 = numpy.mean(sent_1)/numpy.linalg.norm(sent_1) # average the vectors for each word into a single vector and normalize it

similarity_sent_1_and_sent_2 = numpy.inner(sent_1, sent_2)  # calculate cosine similarity
```

You can just do this to calculate the similarities between two sentences. The code above will be efficient and fast and take advantage of the way Magnitude works. I see no reason to create a set of words and iterate over the whole model.
