### ISSUE TITLE
Bad Magnitude File

### ISSUE THREAD

**Issue by yassin-taskin** [plasticityai/magnitude#3]
The file
English Wikipedia 2017 + subword 16B
heavy model

http://magnitude.plasticity.ai/fasttext+approx/wiki-news-300d-1M-subword.magnitude

seems to have an empty magnitude table.
When i execute len(vectors) it gives back 0
Also in the program" DB Browser for SQLite"  the table is empty.

The other file
http://magnitude.plasticity.ai/fasttext+approx/wiki-news-300d-1M.magnitude
works fine and the magnitude table is not empty.

**Comment by AjayP13** [comment]
Hi,

I cannot reproduce this. That file seems to work fine for me in Magnitude and the SQLite table for magnitude does not appear to be empty.

<img width="614" alt="image" src="https://user-images.githubusercontent.com/5404177/37248629-3a203da0-248c-11e8-8c37-1fbb710b8800.png">

Can you re-download the file and make sure that it didn't get corrupted while downloading or didn't partially download. If it continues to be an issue, can you post more information regarding your operating system version, Python version, and SQLite version?

**Comment by yassin-taskin** [comment]
Ok it seems to work on another pc. . Don't know what exactly is wrong.
