### ISSUE TITLE
Encoding error at conversion

### ISSUE THREAD

**Issue by Xhattam** [plasticityai/magnitude#33]
Hi Ajay !

I have a .bin sentence embedding file generated as word2vec .bin format, and am trying to use the magnitude converter utility to convert it to a .magnitude file.

I believe a .bin generated with fastText should work for conversion, as mentioned in your documentation, but I'm hitting an encoding error in the file attached.

Could you shed some light on this, since there's no encoding option for the converter ?

Is there a solution ?

Thanks !

Jessica T
[magnitude_encoding_error.txt](https://github.com/plasticityai/magnitude/files/2534749/magnitude_encoding_error.txt)

**Comment by AjayP13** [comment]
Actually fastText `.bin`'s are not supported unfortunately only word2vec `.bins`. Is it easy enough to convert these to the `.vec` format Facebook also releases? We support those. If not, I can look into figuring out how to support these in the future.

**Comment by Xhattam** [comment]
Hi Ajay, 

Sorry I took a while to get back to you about this.
It seems they only published this .bin file, which I can only read with sent2vec in python. 
I tried reading it with other gensim libraries, hoping I might be able to convert it to a word2vec bin instead of a fastText .bin, but no success so far :/ 
I'll keep digging and will let you know a workaround if I find one, in case anyone else tries this !

Cheers

JT
