### ISSUE TITLE
Segmentation fault on pymagnitude.converter with -a flag

### ISSUE THREAD

**Issue by svakulenk0** [plasticityai/magnitude#34]
Hi! I am getting the Segmentation fault (core dumped) error when creating approximate nearest neighbors index...

**Comment by AjayP13** [comment]
Hi Svitlana,

Magnitude actually uses [Spotify's annoy](https://github.com/spotify/annoy/) library to build the approximate index. A segmentation fault implies something might be going wrong inside annoy's native code. I would imagine it is an out-of-memory issue on your machine, it actually takes a lot of memory to build the index (but once you have a .magnitude file, you can use the library on very low memory machines!). So I would recommend maybe trying to convert it on an Amazon EC2 instance with higher memory.

If you think this is not the issue or you want me to convert it. Upload the file somewhere and send it to me at ajay@plasticity.ai and I can convert it for you.

**Comment by svakulenk0** [comment]
Hi Ajay, thank you for the feedback! The embeddings I was trying to convert are publicly available here http://data.dws.informatik.uni-mannheim.de/rdf2vec/models/DBpedia/2016-04/GlobalVectors/11_pageRankSplit/DBpediaVecotrs200_20Shuffle.txt I have tried to run the pymagnitude converter on it on a 16GB machine but it repeatedly gets killed at the point of creating the approximate nearest neighbors index. It would be great if you could try to convert this file for me! Thank you.

**Comment by arianpasquali** [comment]
@svakulenk0 @AjayP13  samething here. I ve tried to convert my pre-trained model (21gb) using pymagnitude but it gets killed when it reaches 87%. I have plenty of memory and power but it keeps failing without using all my RAM.

I gave up pymagitude and decide to do use Annoy directly.

I have a corpora that is not that big (~10 million sentences ~1.4Gb) and I m embedding and building the index using Annoy. When it reaches around 2.3 million items in the index it gaves me Segmentation Fault. I'm not sure how to work around that besides downsize my corpora. It works fine for smaller corpora.
I wish I could find a way to overcome this and be able to use all my data.

**Comment by AjayP13** [comment]
Interesting @svakulenk0, @arianpasquali. I'll give your data a go on a larger machine @svakulenk0, but if what @arianpasquali is saying is correct, it doesn't appear to be a RAM issue, but rather a possible bug with Annoy with large data.

@arianpasquali  since you got the crash using Annoy directly, do you think you could open an issue against [https://github.com/spotify/annoy](https://github.com/spotify/annoy) and see if Erik (author of Annoy) has seen this bug before. If it's a bug in that library, once it is fixed, I can pull in that change into Magnitude. If it's an easy fix I'm willing to PR a fix on annoy.

**Comment by AjayP13** [comment]
I see one possible issue, it looks like Annoy is using an [signed int32 for the id of the vector ](https://github.com/spotify/annoy/blob/master/src/annoymodule.cc#L127)so if you have more than ~2.1 *billion* vectors it will probably start overflowing when creating the approximate index. It seems like you both are operating well below 2 *billion* as you are in the million range. Not, totally sure what is the issue.

**Comment by arianpasquali** [comment]
thank you for your feedback @AjayP13 . 
What you mentioned about the signed int32. 
Even if it is not the case it looks like a good starting point to investigate.

I will run more tests to make sure and open the issue there.

**Comment by AjayP13** [comment]
@svakulenk0 I've kicked off a conversion job on a larger server. I'll let you know when/if it completes.

**Comment by AjayP13** [comment]
Closing this to clear out some issues.
