### ISSUE TITLE
Feature Request: Option to update individual embeddings 

### ISSUE THREAD

**Issue by Santosh-Gupta** [plasticityai/magnitude#58]
As mentioned in this thread https://github.com/plasticityai/magnitude/issues/32

The ability to quickly and easily update individual vectors in a Magnitude object can make this library a powerful tool for sparse training of embeddings. This can be implemented very easily in Pytorch, and fairly straight forward in Keras.

**Comment by AjayP13** [comment]
We cannot do this unfortunately due to the other features of the package, namely the `most_similar` spatial index created by Annoy. That index would have to be updated as well, which is not easy to do, so this is out-of-scope for now.
