### ISSUE TITLE
Merging two magnitude files

### ISSUE THREAD

**Issue by mamprogr** [plasticityai/magnitude#64]
How to merge two magnitude files?
I have Arabic and English embeddings files and I want to merge them into one to be able to measure the similarities.

**Comment by AjayP13** [comment]
No way to merge them, if you have them in `.txt` format you can manually merge (it's not super difficult to do that, just open them in any text editor and copy and paste). Then, once you have the merged `.txt` vector file you can just use the converter to convert that to `.magnitude`
