### ISSUE TITLE
How to calculate the similarity between two vectors quickly?

### ISSUE THREAD

**Issue by tudousponge** [plasticityai/magnitude#68]
Hi! 
I'm a newcomer here, and can anybody tell me how to calculate similarity of two vectors quickly? I wonder the algorithm that pymagnitude use, but I can't figure it out after reading the tutorial.
Thanks!

**Comment by SakigamiYang** [comment]
Hi!
If you are using Python3, I suggest using Scipy. It uses the superfast optimized NumPy for its number crunching (maybe more better with NumPy + MKL, I guess). Function spatial.distance.cosine will calculate the distance between two vectors for you, and you just need let 1 - the distance to be the similarity.

**Comment by acsands13** [comment]
If you're looking for the similarity between keys, you can use:
```python
vectors.similarity("cat", "dog")  # Similarity between "cat" and "dog"
vectors.similarity("cat", ["dog", "tiger"])  # Similarity between "cat" and multiple keys
```
This returns the **cosine similarity** between the vectors for the keys. #70
