### ISSUE TITLE
OperationalError: FTS expression tree is too large (maximum depth 12)

### ISSUE THREAD

**Issue by janimo** [plasticityai/magnitude#7]
Should the caller check the length of the queried words? Passing a very long string like below causes an SQLite error

v.query(1026*'ab')

**Comment by AjayP13** [comment]
Thanks for reporting this @janimo. This is an issue I was mindful of when building this, however, I thought it would be okay given most words fall way beyond this length. Mind sharing your use case?

This is happening due to the out-of-vocabulary lookup. The fix in mind I have for this is to disable the advanced out-of-vocabulary lookup for very long words perhaps. Does this sound reasonable for your use case?

**Comment by janimo** [comment]
It was due to trying to get vectors out of unprocessed and messy text, so definitely a corner case. Disabling OOV lookup for long words sounds ok.

**Comment by bobsaggirty** [comment]
I see that makes sense, we should definitely support that case. Here's the commit / pipeline for the fix I just submitted to master: https://gitlab.com/Plasticity/magnitude/pipelines/19448775. It is currently being tested on our CI servers, but once it gets deployed to PyPI it should be on version 0.1.15. Once that happens, you can upgrade your local installation with `pip install pymagnitude -U` or `pip3 install pymagnitude -U` if using Python 3.

I added a test case to make sure this doesn't break in the future, but please post back here if the fix works for you after upgrading and I'll close out this issue.

**Comment by AjayP13** [comment]
I see that makes sense, we should definitely support that case. Here's the commit / pipeline for the fix I just submitted to master: https://gitlab.com/Plasticity/magnitude/pipelines/19448775. It is currently being tested on our CI servers, but once it gets deployed to PyPI it should be on version 0.1.15. Once that happens, you can upgrade your local installation with pip install pymagnitude -U or pip3 install pymagnitude -U if using Python 3.

I added a test case to make sure this doesn't break in the future, but please post back here if the fix works for you after upgrading and I'll close out this issue.
