### ISSUE TITLE
converting .vec with annoy causes an infinite loop

### ISSUE THREAD

**Issue by johnfarina** [plasticityai/magnitude#9]
Trying to convert a .vec file to .magnitude along with an annoy approximate index falls into an infinte loop whereby it continually prints `100.0%`.

Using the repo's `test/models/fasttext.vec` as a minimal example (though the same behavior occurs with real .vec files):

```bash
$ python -m pymagnitude.converter -i fasttext.vec -o out.magnitude -a  
/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py:125: RuntimeWarning: 'pymagnitude.converter' found in sys.modules after import of package 'pymagnitude', but prior to execution of 'pymagnitude.converter'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Loading vectors... (this may take some time)
Found 5 key(s)
Each vector has 2 dimension(s)
Creating magnitude format...
Writing vectors... (this may take some time)
0% completed
20% completed
40% completed
60% completed
80% completed
Committing written vectors... (this may take some time)
Entropy of dimension 0 is 2.321928
Entropy of dimension 1 is 2.321928
Creating search index... (this may take some time)
Creating spatial search index for dimension 0 (it has high entropy)... (this may take some time)
Creating approximate nearest neighbors index... (this may take some time)
Dumping approximate nearest neighbors index... (this may take some time)
Compressing approximate nearest neighbors index... (this may take some time)
100.0%
100.0%
100.0%           <-- This line prints forever
```

Which suggests that something is amiss in the following loop starting at line 392 of `converter.py`:

```python
for i, chunk in enumerate(iter(partial(ifh.read, chunk_size), '')):
    if i == 0:
        chunk = compressor.begin() + compressor.compress(chunk)
    else:
        chunk = compressor.compress(chunk)
    eprint(str((ifh.tell() / float(full_size)) * 100.0) + "%")
```

Likely unrelated, but I'm not sure what's causing the RuntimeWarning either. It's thrown even without `-a`, and the conversion seems to work just fine in that case.

**Comment by AjayP13** [comment]
Thanks again! This was a bug unique to Python 3, I've added tests on our CI pipeline to test this case now and introduced a fix. The Runtime Warning will still be there (it is unrelated and due to a cyclical import), but it shouldn't be an issue for converting files.

Here's the commit and pipeline:
https://gitlab.com/Plasticity/magnitude/commit/b61020d840d54f0275dd4c9da5b3e0d00d5dcd7c

The change will be out on version 0.1.17.

**Comment by johnfarina** [comment]
Ah excellent, 0.1.17 is now on PYPI and fixes the bug! We can close this issue now.
